name: Git tree checks

on:
  pull_request:
    types: [opened, edited]
  merge_group:
permissions: read-all

jobs:
  check_base_ref:
    name: Only staging may merge into master
    runs-on: ubuntu-latest
    steps:
      - id: not_based_on_master
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.ref == 'master' &&
          github.event.pull_request.head.ref != 'staging'
        run: |
          echo 'Only the `staging` branch is allowed to merge into `master`.'
          echo 'Maybe your PR should be merging into `staging`?'
          exit 1
